# Run: docker-compose up -d
# Connection: Host=localhost;Port=5432;Database=pdf_db;User=postgres;Password=postgres

version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: pdf_processing_db
    restart: always
    environment:
      POSTGRES_DB: pdf_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pdf_processing_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:

